# Generated by Django 5.2.17 on 2026-08-09 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InquiryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=120, verbose_name="表示名"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="送信先 Email"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
            ],
            options={
                "verbose_name": "問い合わせ分類",
                "verbose_name_plural": "問い合わせ分類",
                "ordering": ("sort_order", "display_name"),
            },
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="姓名")),
                ("phone", models.CharField(max_length=60, verbose_name="電話")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "budget_range",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="予算区間"
                    ),
                ),
                (
                    "project_location",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="案件地点"
                    ),
                ),
                (
                    "expected_timing",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="予定時期"
                    ),
                ),
                ("message", models.TextField(verbose_name="メッセージ")),
                (
                    "privacy_agreed",
                    models.BooleanField(verbose_name="個人資料処理に同意"),
                ),
                (
                    "newsletter_opt_in",
                    models.BooleanField(default=False, verbose_name="電子報購読"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "新規"),
                            ("in_progress", "対応中"),
                            ("completed", "完了"),
                            ("spam", "スパム"),
                        ],
                        default="new",
                        max_length=24,
                        verbose_name="ステータス",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "handled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="対応完了日時"
                    ),
                ),
                ("admin_note", models.TextField(blank=True, verbose_name="管理メモ")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inquiries",
                        to="inquiries.inquirycategory",
                        verbose_name="分類",
                    ),
                ),
            ],
            options={
                "verbose_name": "問い合わせ",
                "verbose_name_plural": "問い合わせ",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="inquiries_i_status_38a868_idx",
                    )
                ],
            },
        ),
    ]
