# Generated by Django 5.2.17 on 2026-08-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inquiry",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "客戶諮詢",
                "verbose_name_plural": "客戶諮詢",
            },
        ),
        migrations.AlterModelOptions(
            name="inquirycategory",
            options={
                "ordering": ("sort_order", "display_name"),
                "verbose_name": "諮詢分類",
                "verbose_name_plural": "諮詢分類",
            },
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="admin_note",
            field=models.TextField(blank=True, verbose_name="管理備註"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="budget_range",
            field=models.CharField(blank=True, max_length=160, verbose_name="預算範圍"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="expected_timing",
            field=models.CharField(blank=True, max_length=200, verbose_name="預計時程"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="handled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="處理完成時間"
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="message",
            field=models.TextField(verbose_name="留言內容"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="newsletter_opt_in",
            field=models.BooleanField(default=False, verbose_name="訂閱電子報"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="privacy_agreed",
            field=models.BooleanField(verbose_name="同意個人資料處理"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "新留言"),
                    ("in_progress", "處理中"),
                    ("completed", "已完成"),
                    ("spam", "垃圾訊息"),
                ],
                default="new",
                max_length=24,
                verbose_name="處理狀態",
            ),
        ),
        migrations.AlterField(
            model_name="inquirycategory",
            name="active",
            field=models.BooleanField(default=True, verbose_name="啟用"),
        ),
        migrations.AlterField(
            model_name="inquirycategory",
            name="display_name",
            field=models.CharField(max_length=120, verbose_name="顯示名稱"),
        ),
        migrations.AlterField(
            model_name="inquirycategory",
            name="recipient_email",
            field=models.EmailField(max_length=254, verbose_name="收件 Email"),
        ),
        migrations.AlterField(
            model_name="inquirycategory",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="顯示順序"),
        ),
    ]
