# Generated by Django 5.2.17 on 2026-08-09 00:13

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        default="Rfull", max_length=120, verbose_name="主要品牌名"
                    ),
                ),
                (
                    "public_name",
                    models.CharField(
                        default="靜院居家", max_length=120, verbose_name="公開漢字表記"
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        default="RESTFULL ATELIER",
                        max_length=120,
                        verbose_name="英語表記",
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        blank=True,
                        default="+886-37-750006",
                        max_length=40,
                        verbose_name="電話 1",
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True,
                        default="+886-932526160",
                        max_length=40,
                        verbose_name="電話 2",
                    ),
                ),
                (
                    "general_email",
                    models.EmailField(
                        blank=True,
                        default="rfullshop@gmail.com",
                        max_length=254,
                        verbose_name="一般・購物・注文 Email",
                    ),
                ),
                (
                    "design_email",
                    models.EmailField(
                        blank=True,
                        default="vicky725705@gmail.com",
                        max_length=254,
                        verbose_name="設計相談 Email",
                    ),
                ),
                (
                    "media_email",
                    models.EmailField(
                        blank=True,
                        default="vicky725705@gmail.com",
                        max_length=254,
                        verbose_name="媒体合作 Email",
                    ),
                ),
                (
                    "business_email",
                    models.EmailField(
                        blank=True,
                        default="vicky725705@gmail.com",
                        max_length=254,
                        verbose_name="商業合作 Email",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, verbose_name="Facebook URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram URL"),
                ),
                (
                    "line_official_url",
                    models.URLField(blank=True, verbose_name="LINE公式 URL"),
                ),
                (
                    "line_add_friend_url",
                    models.URLField(blank=True, verbose_name="LINE友達追加 URL"),
                ),
                (
                    "line_service_label",
                    models.CharField(
                        blank=True,
                        default="LINE 客服",
                        max_length=120,
                        verbose_name="LINE客服表示",
                    ),
                ),
                (
                    "line_service_hours",
                    models.CharField(
                        blank=True,
                        default="週一至週五 10:00–18:00",
                        max_length=200,
                        verbose_name="LINE客服時間",
                    ),
                ),
                (
                    "line_after_hours_note",
                    models.CharField(
                        blank=True,
                        default="非營業時間訊息將於下一工作日回覆",
                        max_length=255,
                        verbose_name="非営業時間の補足",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, max_length=120, verbose_name="銀行名"),
                ),
                (
                    "bank_code",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="銀行コード"
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="口座番号"
                    ),
                ),
                (
                    "bank_account_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="口座名義"
                    ),
                ),
                (
                    "taiwan_pay_qr",
                    models.ImageField(
                        blank=True,
                        upload_to="payments/taiwan-pay/",
                        validators=[core.validators.validate_image_upload],
                        verbose_name="Taiwan Pay QR",
                    ),
                ),
                (
                    "checkout_enabled",
                    models.BooleanField(default=False, verbose_name="注文受付を有効化"),
                ),
                (
                    "order_notification_email",
                    models.EmailField(
                        blank=True,
                        default="rfullshop@gmail.com",
                        max_length=254,
                        verbose_name="注文通知 Email",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        default="室內設計、生活器物與閱讀提案，整理屬於自己的生活節奏。",
                        max_length=255,
                        verbose_name="既定 meta description",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "サイト設定",
                "verbose_name_plural": "サイト設定",
            },
        ),
    ]
