# Generated by Django 5.2.17 on 2026-08-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_enable_checkout"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesettings",
            options={"verbose_name": "網站設定", "verbose_name_plural": "網站設定"},
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=120, verbose_name="戶名"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=80, verbose_name="銀行帳號"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="bank_code",
            field=models.CharField(blank=True, max_length=30, verbose_name="銀行代碼"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="bank_name",
            field=models.CharField(blank=True, max_length=120, verbose_name="銀行名稱"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="brand_name",
            field=models.CharField(
                default="Rfull", max_length=120, verbose_name="主要品牌名稱"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="checkout_enabled",
            field=models.BooleanField(default=True, verbose_name="啟用結帳與訂單功能"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="design_email",
            field=models.EmailField(
                blank=True,
                default="vicky725705@gmail.com",
                max_length=254,
                verbose_name="設計諮詢 Email",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="english_name",
            field=models.CharField(
                default="RESTFULL ATELIER", max_length=120, verbose_name="英文名稱"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="general_email",
            field=models.EmailField(
                blank=True,
                default="rfullshop@gmail.com",
                max_length=254,
                verbose_name="一般、購物與訂單 Email",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="line_add_friend_url",
            field=models.URLField(blank=True, verbose_name="LINE 加好友網址"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="line_after_hours_note",
            field=models.CharField(
                blank=True,
                default="非營業時間訊息將於下一工作日回覆",
                max_length=255,
                verbose_name="非營業時間說明",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="line_official_url",
            field=models.URLField(blank=True, verbose_name="LINE 官方帳號網址"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="line_service_label",
            field=models.CharField(
                blank=True,
                default="LINE 客服",
                max_length=120,
                verbose_name="LINE 客服標示",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="media_email",
            field=models.EmailField(
                blank=True,
                default="vicky725705@gmail.com",
                max_length=254,
                verbose_name="媒體合作 Email",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_description",
            field=models.CharField(
                default="室內設計、生活器物與閱讀提案，整理屬於自己的生活節奏。",
                max_length=255,
                verbose_name="預設 meta description",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="order_notification_email",
            field=models.EmailField(
                blank=True,
                default="rfullshop@gmail.com",
                max_length=254,
                verbose_name="訂單通知 Email",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="public_name",
            field=models.CharField(
                default="靜院居家", max_length=120, verbose_name="公開顯示名稱"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
    ]
