# Generated by Django 5.2.17 on 2026-08-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_sitesettings_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("access", "查詢／匯出"),
                            ("correction", "更正"),
                            ("restrict", "停止處理"),
                            ("anonymize", "匿名化／刪除"),
                        ],
                        max_length=20,
                        verbose_name="申請類型",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="聯絡 Email")),
                (
                    "order_reference",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="訂單編號"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "已受理"),
                            ("verifying", "本人確認中"),
                            ("processing", "處理中"),
                            ("completed", "完成"),
                            ("rejected", "拒絕／依法保留"),
                        ],
                        default="received",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                ("details", models.TextField(blank=True, verbose_name="申請內容")),
                (
                    "operator_note",
                    models.TextField(blank=True, verbose_name="處理紀錄"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="本人確認時間"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成時間"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="受理時間"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="business_address",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="營業所地址"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="business_hours",
            field=models.CharField(blank=True, max_length=200, verbose_name="營業時間"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="business_legal_name",
            field=models.CharField(
                blank=True, max_length=180, verbose_name="事業者名稱"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="business_representative",
            field=models.CharField(blank=True, max_length=120, verbose_name="負責人"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="customer_data_retention_days",
            field=models.PositiveIntegerField(
                default=2555, verbose_name="顧客個資保存天數"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="privacy_contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="個資權利聯絡信箱"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="returns_contact",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="退換貨／問い合わせ窓口"
            ),
        ),
        migrations.CreateModel(
            name="RateLimitBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=40, verbose_name="範圍")),
                ("key_hash", models.CharField(max_length=64, verbose_name="識別雜湊")),
                (
                    "window_started_at",
                    models.DateTimeField(db_index=True, verbose_name="計時開始"),
                ),
                ("count", models.PositiveIntegerField(default=0, verbose_name="次數")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scope", "window_started_at"],
                        name="core_rateli_scope_cbc4d6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "key_hash", "window_started_at"),
                        name="unique_rate_limit_bucket",
                    )
                ],
            },
        ),
    ]
