# Generated by Django 5.2.17 on 2026-08-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_privacyrequest_sitesettings_business_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="returns_contact",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="退換貨／諮詢窗口"
            ),
        ),
    ]
