# Generated by Django 5.2.17 on 2026-09-08 14:40

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_sitesettings_business_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_image",
            field=models.ImageField(
                blank=True,
                upload_to="site/about/",
                validators=[core.validators.validate_image_upload],
                verbose_name="關於頁主要圖片",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_image_alt",
            field=models.CharField(
                blank=True,
                default="靜院工作室",
                max_length=255,
                verbose_name="關於頁圖片替代文字",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_image_position",
            field=models.CharField(
                choices=[
                    ("center", "置中"),
                    ("top", "靠上"),
                    ("bottom", "靠下"),
                    ("left", "靠左"),
                    ("right", "靠右"),
                ],
                default="center",
                max_length=10,
                verbose_name="關於頁圖片位置",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_intro",
            field=models.TextField(
                blank=True,
                default="從 2019 年第一個住宅案開始，我們相信家不只是空間，而是一個人對自己最誠實的投影。\n\n所以我們從規劃動線開始，也從挑選一只茶杯開始——因為每一件進入你家的東西，都會和你一起呼吸。\n\n這也是為什麼，在靜院，設計與選物從不分開。",
                verbose_name="關於頁介紹",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_timeline_heading",
            field=models.CharField(
                blank=True,
                default="2019 —",
                max_length=100,
                verbose_name="關於頁沿革標題",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_timeline_text",
            field=models.TextField(
                blank=True,
                default="從第一個住宅案，到第一本季刊、第一只被帶回家的杯子。靜院仍在練習，如何把空間、器物與人的日常，安靜地放在一起。",
                verbose_name="關於頁沿革內文",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_title",
            field=models.CharField(
                blank=True,
                default="靜院可以是\n室內設計的規劃者，\n更是生活家居的實踐家。",
                max_length=240,
                verbose_name="關於頁標題",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="brand_logo",
            field=models.ImageField(
                blank=True,
                upload_to="site/branding/",
                validators=[core.validators.validate_image_upload],
                verbose_name="網站標誌",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="brand_logo_alt",
            field=models.CharField(
                blank=True,
                default="Rfull Home",
                max_length=160,
                verbose_name="網站標誌替代文字",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_og_image",
            field=models.ImageField(
                blank=True,
                upload_to="site/seo/",
                validators=[core.validators.validate_image_upload],
                verbose_name="預設 OGP／社群分享圖片",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_copyright",
            field=models.CharField(
                blank=True,
                default="© 2026 靜院居家",
                max_length=160,
                verbose_name="頁尾版權文字",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_message",
            field=models.TextField(
                blank=True,
                default="自己是自己的典範。\n從一扇窗、一只器皿、一盞茶開始，\n把家養成自己的道場。",
                verbose_name="頁尾品牌介紹",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_tagline",
            field=models.CharField(
                blank=True,
                default="室內・居家・生活",
                max_length=120,
                verbose_name="頁首品牌短句",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_brand_cta_label",
            field=models.CharField(
                blank=True,
                default="讀我們的故事 →",
                max_length=120,
                verbose_name="首頁品牌連結文字",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_brand_message",
            field=models.CharField(
                blank=True,
                default="我們不只選擇器物，也整理生活的節奏。",
                max_length=255,
                verbose_name="首頁品牌說明",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_brand_quote",
            field=models.CharField(
                blank=True,
                default="讓家成為一個\n可以慢下來的地方。",
                max_length=220,
                verbose_name="首頁品牌主張",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_featured_aside",
            field=models.CharField(
                blank=True,
                default="一處住宅，也是一種生活練習。",
                max_length=220,
                verbose_name="首頁精選作品短文",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_featured_title",
            field=models.CharField(
                blank=True,
                default="讓光，慢慢住進來",
                max_length=180,
                verbose_name="首頁精選作品標題",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_hero_alt",
            field=models.CharField(
                blank=True,
                default="靜院居家空間與生活提案",
                max_length=255,
                verbose_name="首頁 Hero 圖片替代文字",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_hero_description",
            field=models.TextField(
                blank=True,
                default="可以安身的處所，可以清歡的宅第。\n靜院是室內設計的規劃者，\n更是生活家居的實踐家。",
                verbose_name="首頁 Hero 說明",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_hero_eyebrow",
            field=models.CharField(
                blank=True,
                default="靜院選集・Rfull",
                max_length=160,
                verbose_name="首頁 Hero 小標",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_hero_image",
            field=models.ImageField(
                blank=True,
                upload_to="site/home/",
                validators=[core.validators.validate_image_upload],
                verbose_name="首頁 Hero 圖片",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_hero_position",
            field=models.CharField(
                choices=[
                    ("center", "置中"),
                    ("top", "靠上"),
                    ("bottom", "靠下"),
                    ("left", "靠左"),
                    ("right", "靠右"),
                ],
                default="center",
                max_length=10,
                verbose_name="首頁 Hero 圖片位置",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_hero_title",
            field=models.CharField(
                blank=True,
                default="靜處安身",
                max_length=120,
                verbose_name="首頁 Hero 標題",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_hero_title_accent",
            field=models.CharField(
                blank=True,
                default="院宅清歡",
                max_length=120,
                verbose_name="首頁 Hero 第二行標題",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_shop_cta_label",
            field=models.CharField(
                blank=True,
                default="進入 靜及第 Online Shop →",
                max_length=120,
                verbose_name="首頁購物按鈕文字",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_works_cta_label",
            field=models.CharField(
                blank=True,
                default="室內設計作品集",
                max_length=120,
                verbose_name="首頁作品按鈕文字",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="publications_headline",
            field=models.CharField(
                blank=True,
                default="每季\n一本\n安靜的書",
                max_length=160,
                verbose_name="出版品頁主標",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="publications_intro_text",
            field=models.TextField(
                blank=True,
                default="我們將空間裡微小的發現，編成一本可以帶回家、慢慢閱讀的書。",
                verbose_name="出版品頁介紹",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="publications_note_quote",
            field=models.CharField(
                blank=True,
                default="清歡不是什麼都沒有，\n而是知道什麼已經足夠。",
                max_length=220,
                verbose_name="出版品頁引言",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="publications_note_text",
            field=models.CharField(
                blank=True,
                default="記錄光落下的位置，也記錄器物被每日使用後的表情。",
                max_length=255,
                verbose_name="出版品頁引言說明",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shop_featured_aside",
            field=models.CharField(
                blank=True,
                default="適合在日常裡，慢慢開始使用。",
                max_length=220,
                verbose_name="購物首頁精選短文",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shop_featured_title",
            field=models.CharField(
                blank=True,
                default="這個月特別想介紹的",
                max_length=180,
                verbose_name="購物首頁精選標題",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shop_hero_alt",
            field=models.CharField(
                blank=True,
                default="靜及第生活器物選",
                max_length=255,
                verbose_name="購物首頁 Hero 圖片替代文字",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shop_hero_description",
            field=models.TextField(
                blank=True,
                default="從一只晨飲杯到一方亞麻桌巾，\n每一樣都經過靜院的手，\n住進我們自己的家中使用。",
                verbose_name="購物首頁 Hero 說明",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shop_hero_eyebrow",
            field=models.CharField(
                blank=True,
                default="RFULL・OBJECTS",
                max_length=160,
                verbose_name="購物首頁 Hero 小標",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shop_hero_image",
            field=models.ImageField(
                blank=True,
                upload_to="site/shop/",
                validators=[core.validators.validate_image_upload],
                verbose_name="購物首頁 Hero 圖片",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shop_hero_position",
            field=models.CharField(
                choices=[
                    ("center", "置中"),
                    ("top", "靠上"),
                    ("bottom", "靠下"),
                    ("left", "靠左"),
                    ("right", "靠右"),
                ],
                default="center",
                max_length=10,
                verbose_name="購物首頁 Hero 圖片位置",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shop_hero_title",
            field=models.CharField(
                blank=True,
                default="慢生活的\n器物清單",
                max_length=160,
                verbose_name="購物首頁 Hero 標題",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shop_logo",
            field=models.ImageField(
                blank=True,
                upload_to="site/branding/",
                validators=[core.validators.validate_image_upload],
                verbose_name="購物網站標誌",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shop_story_alt",
            field=models.CharField(
                blank=True,
                default="清晨的一杯茶",
                max_length=255,
                verbose_name="購物首頁季節文章圖片替代文字",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shop_story_image",
            field=models.ImageField(
                blank=True,
                upload_to="site/shop/",
                validators=[core.validators.validate_image_upload],
                verbose_name="購物首頁季節文章圖片",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shop_story_position",
            field=models.CharField(
                choices=[
                    ("center", "置中"),
                    ("top", "靠上"),
                    ("bottom", "靠下"),
                    ("left", "靠左"),
                    ("right", "靠右"),
                ],
                default="center",
                max_length=10,
                verbose_name="購物首頁季節文章圖片位置",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shop_story_quote",
            field=models.CharField(
                blank=True,
                default="器物不是裝飾。",
                max_length=180,
                verbose_name="購物首頁季節文章引言",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shop_story_text",
            field=models.TextField(
                blank=True,
                default="每天拿起、清洗、收回原位的過程，才會讓它慢慢成為生活的一部分。",
                verbose_name="購物首頁季節文章內文",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shop_story_title",
            field=models.CharField(
                blank=True,
                default="清晨的\n一杯茶",
                max_length=160,
                verbose_name="購物首頁季節文章標題",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="works_consultation_cta",
            field=models.CharField(
                blank=True,
                default="設計諮詢 →",
                max_length=100,
                verbose_name="室內設計頁諮詢按鈕",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="works_consultation_text",
            field=models.CharField(
                blank=True,
                default="一個好住的家，從理解你的日常開始。",
                max_length=220,
                verbose_name="室內設計頁諮詢文案",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="works_intro_statement",
            field=models.CharField(
                blank=True,
                default="自己是\n自己的典範",
                max_length=160,
                verbose_name="室內設計頁主張",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="works_intro_title",
            field=models.CharField(
                blank=True,
                default="靜院室內設計",
                max_length=160,
                verbose_name="室內設計頁標題",
            ),
        ),
    ]
