# Generated by Django 5.2.17 on 2026-09-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_sitesettings_about_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="contact_lead",
            field=models.CharField(
                blank=True,
                default="歡迎來信，\n我們會靜靜地回覆你。",
                max_length=220,
                verbose_name="聯絡頁引言",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_title",
            field=models.CharField(
                blank=True,
                default="聯絡我們",
                max_length=160,
                verbose_name="聯絡頁標題",
            ),
        ),
    ]
