# Generated by Django 5.2.17 on 2026-08-09 00:13

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="カテゴリ名")),
                (
                    "slug",
                    models.SlugField(max_length=140, unique=True, verbose_name="slug"),
                ),
                (
                    "english_name",
                    models.CharField(blank=True, max_length=160, verbose_name="英語名"),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "subcategories",
                    models.JSONField(
                        blank=True, default=list, verbose_name="絞り込み項目"
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        blank=True,
                        default="linen",
                        max_length=40,
                        verbose_name="プレースホルダー色",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "商品カテゴリ",
                "verbose_name_plural": "商品カテゴリ",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=220, verbose_name="商品名")),
                (
                    "slug",
                    models.SlugField(max_length=240, unique=True, verbose_name="slug"),
                ),
                (
                    "sku",
                    models.CharField(max_length=80, unique=True, verbose_name="SKU"),
                ),
                (
                    "maker",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="製作者・ブランド"
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="シリーズ"
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="絞り込み項目"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="短い説明"
                    ),
                ),
                ("description", models.TextField(verbose_name="商品説明")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="価格"
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="在庫")),
                (
                    "is_preorder",
                    models.BooleanField(default=False, verbose_name="預購商品"),
                ),
                (
                    "preorder_note",
                    models.TextField(blank=True, verbose_name="預購注記"),
                ),
                ("care", models.TextField(blank=True, verbose_name="使用と手入れ")),
                (
                    "shipping_note",
                    models.TextField(blank=True, verbose_name="配送・退換注記"),
                ),
                (
                    "maker_story",
                    models.TextField(blank=True, verbose_name="製作者について"),
                ),
                (
                    "badge_label",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="カードラベル"
                    ),
                ),
                (
                    "image_label",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="仮画像ラベル"
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        blank=True,
                        default="linen",
                        max_length=40,
                        verbose_name="仮画像色",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="公開"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.productcategory",
                        verbose_name="カテゴリ",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="products/%Y/%m/",
                        validators=[core.validators.validate_image_upload],
                        verbose_name="画像",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(max_length=255, verbose_name="代替テキスト"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="主画像"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品画像",
                "verbose_name_plural": "商品画像",
                "ordering": ("sort_order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="項目名")),
                ("value", models.CharField(max_length=500, verbose_name="内容")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="catalog.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品仕様",
                "verbose_name_plural": "商品仕様",
                "ordering": ("sort_order", "pk"),
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_published", "sort_order"],
                name="catalog_pro_is_publ_afe672_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("product",),
                name="one_primary_image_per_product",
            ),
        ),
    ]
