# Generated by Django 5.2.17 on 2026-08-10 14:00

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "ordering": ("sort_order", "name"),
                "verbose_name": "商品分類",
                "verbose_name_plural": "商品分類",
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ("sort_order", "pk"),
                "verbose_name": "商品圖片",
                "verbose_name_plural": "商品圖片",
            },
        ),
        migrations.AlterModelOptions(
            name="productspecification",
            options={
                "ordering": ("sort_order", "pk"),
                "verbose_name": "商品規格",
                "verbose_name_plural": "商品規格",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="badge_label",
            field=models.CharField(blank=True, max_length=80, verbose_name="卡片標籤"),
        ),
        migrations.AlterField(
            model_name="product",
            name="care",
            field=models.TextField(blank=True, verbose_name="使用與保養"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.productcategory",
                verbose_name="商品分類",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="商品說明"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_label",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="預留圖片文字"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="maker",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="製作者／品牌"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="maker_story",
            field=models.TextField(blank=True, verbose_name="製作者介紹"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=220, verbose_name="商品名稱"),
        ),
        migrations.AlterField(
            model_name="product",
            name="preorder_note",
            field=models.TextField(blank=True, verbose_name="預購說明"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=0, max_digits=12, verbose_name="售價"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="series",
            field=models.CharField(blank=True, max_length=160, verbose_name="系列"),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipping_note",
            field=models.TextField(blank=True, verbose_name="配送與退換貨說明"),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.CharField(blank=True, max_length=300, verbose_name="簡短說明"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="顯示順序"),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="庫存"),
        ),
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.CharField(blank=True, max_length=120, verbose_name="篩選項目"),
        ),
        migrations.AlterField(
            model_name="product",
            name="tone",
            field=models.CharField(
                blank=True, default="linen", max_length=40, verbose_name="預留圖片色調"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="description",
            field=models.TextField(blank=True, verbose_name="分類說明"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="english_name",
            field=models.CharField(blank=True, max_length=160, verbose_name="英文名稱"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="啟用"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(max_length=120, verbose_name="商品分類名稱"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="顯示順序"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="subcategories",
            field=models.JSONField(blank=True, default=list, verbose_name="篩選項目"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="tone",
            field=models.CharField(
                blank=True, default="linen", max_length=40, verbose_name="預留圖片色調"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(max_length=255, verbose_name="替代文字"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="products/%Y/%m/",
                validators=[core.validators.validate_image_upload],
                verbose_name="圖片",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="主要圖片"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="顯示順序"),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="label",
            field=models.CharField(max_length=100, verbose_name="規格名稱"),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="顯示順序"),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="value",
            field=models.CharField(max_length=500, verbose_name="規格內容"),
        ),
    ]
