# Generated by Django 5.2.17 on 2026-08-11 02:28

from django.db import migrations, models


def quarantine_invalid_products(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    # Preserve every row but prevent legacy invalid prices/inventory from
    # blocking deploy or remaining publicly purchasable before constraints land.
    Product.objects.filter(price__lt=0).update(price=0, is_published=False)
    Product.objects.filter(stock__lt=0).update(stock=0, is_published=False)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_productcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="preorder_delivery_estimate",
            field=models.CharField(
                blank=True, max_length=180, verbose_name="預計交付時間"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="preorder_limit",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="預購上限"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sale_ends_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="結束販售"),
        ),
        migrations.AddField(
            model_name="product",
            name="sale_starts_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="開始販售"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to="products/thumbnails/%Y/%m/",
                verbose_name="縮圖",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="catalog_pro_sku_2c4c34_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["sale_starts_at", "sale_ends_at"],
                name="catalog_pro_sale_st_8f76a1_idx",
            ),
        ),
        migrations.RunPython(quarantine_invalid_products, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)), name="product_price_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock__gte", 0)), name="product_stock_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sale_ends_at__isnull", True),
                    ("sale_starts_at__isnull", True),
                    ("sale_ends_at__gt", models.F("sale_starts_at")),
                    _connector="OR",
                ),
                name="product_sale_window_valid",
            ),
        ),
    ]
