# Generated by Django 5.2.17 on 2026-09-19 07:27

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productimage_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='thumbnail_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='分類縮圖替代文字'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='thumbnail_focus_x',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='分類縮圖焦點 X'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='thumbnail_focus_y',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='分類縮圖焦點 Y'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='catalog/categories/%Y/%m/', validators=[core.validators.validate_image_upload], verbose_name='分類縮圖'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.CheckConstraint(condition=models.Q(('thumbnail_focus_x__range', (0, 100))), name='catalog_category_thumbnail_focus_x_range'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.CheckConstraint(condition=models.Q(('thumbnail_focus_y__range', (0, 100))), name='catalog_category_thumbnail_focus_y_range'),
        ),
    ]
