# Generated by Django 5.2.17 on 2026-08-09 00:13

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InteriorProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220, verbose_name="タイトル")),
                (
                    "slug",
                    models.SlugField(max_length=240, unique=True, verbose_name="slug"),
                ),
                (
                    "english_title",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="英語タイトル"
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="作品分類"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=160, verbose_name="場所"),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="年"
                    ),
                ),
                (
                    "area",
                    models.CharField(blank=True, max_length=100, verbose_name="面積"),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="スタイル"
                    ),
                ),
                ("description", models.TextField(verbose_name="説明")),
                (
                    "concept_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="コンセプト見出し"
                    ),
                ),
                (
                    "design_notes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="設計ノート"
                    ),
                ),
                (
                    "materials",
                    models.JSONField(blank=True, default=list, verbose_name="素材一覧"),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        upload_to="projects/%Y/%m/",
                        validators=[core.validators.validate_image_upload],
                        verbose_name="メイン画像",
                    ),
                ),
                (
                    "image_label",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="仮画像ラベル"
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        blank=True,
                        default="bamboo",
                        max_length=40,
                        verbose_name="仮画像色",
                    ),
                ),
                ("published", models.BooleanField(default=False, verbose_name="公開")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "室内設計作品",
                "verbose_name_plural": "室内設計作品",
                "ordering": ("sort_order", "-year", "title"),
            },
        ),
        migrations.CreateModel(
            name="PolicyPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220, verbose_name="タイトル")),
                (
                    "slug",
                    models.SlugField(max_length=240, unique=True, verbose_name="slug"),
                ),
                ("body", models.TextField(blank=True, verbose_name="本文")),
                ("published", models.BooleanField(default=False, verbose_name="公開")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ポリシーページ",
                "verbose_name_plural": "ポリシーページ",
                "ordering": ("sort_order", "title"),
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_number", models.CharField(max_length=40, verbose_name="号数")),
                ("title", models.CharField(max_length=220, verbose_name="タイトル")),
                (
                    "slug",
                    models.SlugField(max_length=240, unique=True, verbose_name="slug"),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="サブタイトル"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ページ数"
                    ),
                ),
                (
                    "published_date",
                    models.DateField(blank=True, null=True, verbose_name="刊行日"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        upload_to="publications/%Y/%m/",
                        validators=[core.validators.validate_image_upload],
                        verbose_name="表紙画像",
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        blank=True,
                        default="rice",
                        max_length=40,
                        verbose_name="仮画像色",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="特集表示"),
                ),
                ("published", models.BooleanField(default=False, verbose_name="公開")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "出版物",
                "verbose_name_plural": "出版物",
                "ordering": ("sort_order", "-published_date", "issue_number"),
            },
        ),
        migrations.CreateModel(
            name="InteriorProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="projects/gallery/%Y/%m/",
                        validators=[core.validators.validate_image_upload],
                        verbose_name="画像",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(max_length=255, verbose_name="代替テキスト"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="キャプション"
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        blank=True,
                        default="linen",
                        max_length=40,
                        verbose_name="仮画像色",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content.interiorproject",
                        verbose_name="作品",
                    ),
                ),
            ],
            options={
                "verbose_name": "作品画像",
                "verbose_name_plural": "作品画像",
                "ordering": ("sort_order", "pk"),
            },
        ),
    ]
