# Generated by Django 5.2.17 on 2026-08-10 14:00

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interiorproject",
            options={
                "ordering": ("sort_order", "-year", "title"),
                "verbose_name": "室內設計作品",
                "verbose_name_plural": "室內設計作品",
            },
        ),
        migrations.AlterModelOptions(
            name="interiorprojectimage",
            options={
                "ordering": ("sort_order", "pk"),
                "verbose_name": "作品圖片",
                "verbose_name_plural": "作品圖片",
            },
        ),
        migrations.AlterModelOptions(
            name="policypage",
            options={
                "ordering": ("sort_order", "title"),
                "verbose_name": "政策頁面",
                "verbose_name_plural": "政策頁面",
            },
        ),
        migrations.AlterModelOptions(
            name="publication",
            options={
                "ordering": ("sort_order", "-published_date", "issue_number"),
                "verbose_name": "出版刊物",
                "verbose_name_plural": "出版刊物",
            },
        ),
        migrations.AlterField(
            model_name="interiorproject",
            name="concept_title",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="設計概念標題"
            ),
        ),
        migrations.AlterField(
            model_name="interiorproject",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="interiorproject",
            name="description",
            field=models.TextField(verbose_name="作品說明"),
        ),
        migrations.AlterField(
            model_name="interiorproject",
            name="design_notes",
            field=models.JSONField(blank=True, default=list, verbose_name="設計筆記"),
        ),
        migrations.AlterField(
            model_name="interiorproject",
            name="english_title",
            field=models.CharField(blank=True, max_length=240, verbose_name="英文標題"),
        ),
        migrations.AlterField(
            model_name="interiorproject",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                upload_to="projects/%Y/%m/",
                validators=[core.validators.validate_image_upload],
                verbose_name="主要圖片",
            ),
        ),
        migrations.AlterField(
            model_name="interiorproject",
            name="image_label",
            field=models.CharField(
                blank=True, max_length=180, verbose_name="預留圖片文字"
            ),
        ),
        migrations.AlterField(
            model_name="interiorproject",
            name="location",
            field=models.CharField(blank=True, max_length=160, verbose_name="地點"),
        ),
        migrations.AlterField(
            model_name="interiorproject",
            name="materials",
            field=models.JSONField(blank=True, default=list, verbose_name="材質列表"),
        ),
        migrations.AlterField(
            model_name="interiorproject",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="顯示順序"),
        ),
        migrations.AlterField(
            model_name="interiorproject",
            name="style",
            field=models.CharField(blank=True, max_length=160, verbose_name="設計風格"),
        ),
        migrations.AlterField(
            model_name="interiorproject",
            name="title",
            field=models.CharField(max_length=220, verbose_name="作品標題"),
        ),
        migrations.AlterField(
            model_name="interiorproject",
            name="tone",
            field=models.CharField(
                blank=True, default="bamboo", max_length=40, verbose_name="預留圖片色調"
            ),
        ),
        migrations.AlterField(
            model_name="interiorproject",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
        migrations.AlterField(
            model_name="interiorproject",
            name="year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="年份"
            ),
        ),
        migrations.AlterField(
            model_name="interiorprojectimage",
            name="alt_text",
            field=models.CharField(max_length=255, verbose_name="替代文字"),
        ),
        migrations.AlterField(
            model_name="interiorprojectimage",
            name="caption",
            field=models.CharField(blank=True, max_length=255, verbose_name="圖片說明"),
        ),
        migrations.AlterField(
            model_name="interiorprojectimage",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="projects/gallery/%Y/%m/",
                validators=[core.validators.validate_image_upload],
                verbose_name="圖片",
            ),
        ),
        migrations.AlterField(
            model_name="interiorprojectimage",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="顯示順序"),
        ),
        migrations.AlterField(
            model_name="interiorprojectimage",
            name="tone",
            field=models.CharField(
                blank=True, default="linen", max_length=40, verbose_name="預留圖片色調"
            ),
        ),
        migrations.AlterField(
            model_name="policypage",
            name="body",
            field=models.TextField(blank=True, verbose_name="內文"),
        ),
        migrations.AlterField(
            model_name="policypage",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="顯示順序"),
        ),
        migrations.AlterField(
            model_name="policypage",
            name="title",
            field=models.CharField(max_length=220, verbose_name="頁面標題"),
        ),
        migrations.AlterField(
            model_name="policypage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                upload_to="publications/%Y/%m/",
                validators=[core.validators.validate_image_upload],
                verbose_name="封面圖片",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="description",
            field=models.TextField(blank=True, verbose_name="出版說明"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="featured",
            field=models.BooleanField(default=False, verbose_name="精選顯示"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="issue_number",
            field=models.CharField(max_length=40, verbose_name="期號"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="page_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="頁數"
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="published_date",
            field=models.DateField(blank=True, null=True, verbose_name="出版日期"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="顯示順序"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="subtitle",
            field=models.CharField(blank=True, max_length=300, verbose_name="副標題"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.CharField(max_length=220, verbose_name="標題"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="tone",
            field=models.CharField(
                blank=True, default="rice", max_length=40, verbose_name="預留圖片色調"
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
    ]
