# Generated by Django 5.2.17 on 2026-08-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_interiorproject_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policypage",
            name="effective_date",
            field=models.DateField(blank=True, null=True, verbose_name="生效日期"),
        ),
        migrations.AddField(
            model_name="policypage",
            name="legal_reviewed",
            field=models.BooleanField(default=False, verbose_name="事業者法務確認済み"),
        ),
        migrations.AddField(
            model_name="policypage",
            name="version",
            field=models.CharField(blank=True, max_length=40, verbose_name="版本"),
        ),
    ]
