# Generated by Django 5.2.17 on 2026-08-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_install_policy_drafts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policypage",
            name="legal_reviewed",
            field=models.BooleanField(default=False, verbose_name="業者法務已確認"),
        ),
    ]
