# Generated by Django 5.2.17 on 2026-09-13 10:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def normalize_existing_gallery_order(apps, schema_editor):
    image_model = apps.get_model("content", "InteriorProjectImage")
    project_ids = (
        image_model.objects.order_by().values_list("project_id", flat=True).distinct()
    )
    for project_id in project_ids:
        if project_id is None:
            continue
        image_ids = (
            image_model.objects.filter(project_id=project_id)
            .order_by("sort_order", "pk")
            .values_list("pk", flat=True)
        )
        for index, image_id in enumerate(image_ids):
            image_model.objects.filter(pk=image_id).update(sort_order=index)


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_localize_public_policy_drafts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="interiorprojectimage",
            name="content_type",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Content-Type"
            ),
        ),
        migrations.AddField(
            model_name="interiorprojectimage",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="建立時間",
            ),
        ),
        migrations.AddField(
            model_name="interiorprojectimage",
            name="file_size",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="檔案大小"
            ),
        ),
        migrations.AddField(
            model_name="interiorprojectimage",
            name="height",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="高度"
            ),
        ),
        migrations.AddField(
            model_name="interiorprojectimage",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255, verbose_name="原始檔名"),
        ),
        migrations.AddField(
            model_name="interiorprojectimage",
            name="upload_session",
            field=models.UUIDField(
                blank=True, db_index=True, null=True, verbose_name="上傳工作階段"
            ),
        ),
        migrations.AddField(
            model_name="interiorprojectimage",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("pending", "上傳待確認"),
                    ("temporary", "暫存"),
                    ("attached", "已連結作品"),
                    ("deletion_pending", "等待刪除"),
                ],
                default="attached",
                max_length=24,
                verbose_name="上傳狀態",
            ),
        ),
        migrations.AddField(
            model_name="interiorprojectimage",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_project_images",
                to=settings.AUTH_USER_MODEL,
                verbose_name="上傳者",
            ),
        ),
        migrations.AddField(
            model_name="interiorprojectimage",
            name="width",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="寬度"
            ),
        ),
        migrations.AlterField(
            model_name="interiorprojectimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=255, verbose_name="替代文字"),
        ),
        migrations.AlterField(
            model_name="interiorprojectimage",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="content.interiorproject",
                verbose_name="作品",
            ),
        ),
        migrations.RunPython(
            normalize_existing_gallery_order,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="interiorprojectimage",
            index=models.Index(
                fields=["project", "upload_status", "sort_order"],
                name="content_ipi_project_idx",
            ),
        ),
    ]
