# Generated by Django 5.2.17 on 2026-09-14 03:12

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_interior_project_image_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="interiorproject",
            name="featured_image_focus_x",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="主要圖片焦點 X",
            ),
        ),
        migrations.AddField(
            model_name="interiorproject",
            name="featured_image_focus_y",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="主要圖片焦點 Y",
            ),
        ),
        migrations.AddField(
            model_name="interiorprojectimage",
            name="focus_x",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="圖片焦點 X",
            ),
        ),
        migrations.AddField(
            model_name="interiorprojectimage",
            name="focus_y",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="圖片焦點 Y",
            ),
        ),
        migrations.AddConstraint(
            model_name="interiorproject",
            constraint=models.CheckConstraint(
                condition=models.Q(("featured_image_focus_x__range", (0, 100))),
                name="content_project_featured_focus_x_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="interiorproject",
            constraint=models.CheckConstraint(
                condition=models.Q(("featured_image_focus_y__range", (0, 100))),
                name="content_project_featured_focus_y_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="interiorprojectimage",
            constraint=models.CheckConstraint(
                condition=models.Q(("focus_x__range", (0, 100))),
                name="content_project_image_focus_x_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="interiorprojectimage",
            constraint=models.CheckConstraint(
                condition=models.Q(("focus_y__range", (0, 100))),
                name="content_project_image_focus_y_range",
            ),
        ),
    ]
