# Generated by Django 5.2.17 on 2026-09-14 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_interiorproject_featured_image_focus_x_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="cover_image_focus_x",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="封面圖片焦點 X",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="cover_image_focus_y",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="封面圖片焦點 Y",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="cover_image_height",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="封面圖片高度",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="cover_image_width",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="封面圖片寬度",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.CheckConstraint(
                condition=models.Q(("cover_image_focus_x__range", (0, 100))),
                name="content_publication_cover_focus_x_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.CheckConstraint(
                condition=models.Q(("cover_image_focus_y__range", (0, 100))),
                name="content_publication_cover_focus_y_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cover_image_width__isnull", True),
                    ("cover_image_width__gte", 1),
                    _connector="OR",
                ),
                name="content_publication_cover_width_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cover_image_height__isnull", True),
                    ("cover_image_height__gte", 1),
                    _connector="OR",
                ),
                name="content_publication_cover_height_positive",
            ),
        ),
    ]
