# Generated by Django 5.2.17 on 2026-08-09 00:13

import core.validators
import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("taiwan_pay", "台灣 Pay"),
                            ("credit_card", "クレジットカード"),
                            ("bank_transfer", "銀行振込"),
                            ("paypal", "PayPal"),
                        ],
                        max_length=32,
                        unique=True,
                        verbose_name="方式",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=False, verbose_name="利用可能"),
                ),
                (
                    "display_name",
                    models.CharField(max_length=120, verbose_name="表示名"),
                ),
                ("instructions", models.TextField(blank=True, verbose_name="案内")),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Provider"
                    ),
                ),
                (
                    "qr_image",
                    models.ImageField(
                        blank=True,
                        upload_to="payments/methods/",
                        validators=[core.validators.validate_image_upload],
                        verbose_name="QR画像",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
            ],
            options={
                "verbose_name": "支払方法設定",
                "verbose_name_plural": "支払方法設定",
                "ordering": ("sort_order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_number",
                    models.CharField(
                        default=orders.models.generate_order_number,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="注文番号",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        default=orders.models.generate_access_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="顧客用アクセスキー",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        unique=True,
                        verbose_name="二重送信防止キー",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=160, verbose_name="姓名"),
                ),
                ("phone", models.CharField(max_length=60, verbose_name="電話")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("shipping_information", models.TextField(verbose_name="配送先情報")),
                ("customer_note", models.TextField(blank=True, verbose_name="備考")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="商品合計"
                    ),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="送料",
                    ),
                ),
                (
                    "final_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        editable=False,
                        max_digits=12,
                        null=True,
                        verbose_name="最終金額",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "注文受付"),
                            ("shipping_review", "送料確認中"),
                            ("awaiting_payment", "支払い待ち"),
                            ("paid", "入金済み"),
                            ("preparing", "発送準備中"),
                            ("shipped", "発送済み"),
                            ("completed", "完了"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="received",
                        max_length=32,
                        verbose_name="ステータス",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="入金確認日時"
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="発送日時"
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="配送会社"
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="追跡番号"
                    ),
                ),
                ("admin_note", models.TextField(blank=True, verbose_name="管理メモ")),
                (
                    "inventory_reserved",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="在庫確保済み"
                    ),
                ),
                (
                    "inventory_released",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="在庫復元済み"
                    ),
                ),
            ],
            options={
                "verbose_name": "注文",
                "verbose_name_plural": "注文",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="orders_orde_status_25e057_idx",
                    ),
                    models.Index(fields=["email"], name="orders_orde_email_88c705_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name_snapshot",
                    models.CharField(
                        max_length=220, verbose_name="商品名スナップショット"
                    ),
                ),
                (
                    "sku_snapshot",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="SKUスナップショット"
                    ),
                ),
                (
                    "unit_price_snapshot",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="単価スナップショット",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="数量")),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="小計"
                    ),
                ),
                (
                    "stock_was_reserved",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="通常在庫を確保"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="注文",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="catalog.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "注文明細",
                "verbose_name_plural": "注文明細",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Provider"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="金額",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "保留"),
                            ("awaiting_confirmation", "確認待ち"),
                            ("confirmed", "確認済み"),
                            ("failed", "失敗"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="支払ステータス",
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Provider参照番号"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="入金日時"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="メモ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="注文",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.paymentmethod",
                        verbose_name="支払方法",
                    ),
                ),
            ],
            options={
                "verbose_name": "支払い",
                "verbose_name_plural": "支払い",
                "ordering": ("-created_at",),
            },
        ),
    ]
