# Generated by Django 5.2.17 on 2026-08-09 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_user_id",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="LINE user ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=160, verbose_name="LINE表示名"),
                ),
                (
                    "picture_url",
                    models.URLField(blank=True, verbose_name="プロフィール画像URL"),
                ),
                (
                    "is_friend",
                    models.BooleanField(default=False, verbose_name="友だち"),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, verbose_name="ブロック"),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終ログイン"
                    ),
                ),
                (
                    "friend_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="友だち確認日時"
                    ),
                ),
                (
                    "followed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="友だち追加日時"
                    ),
                ),
                (
                    "unfollowed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ブロック日時"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LINE顧客",
                "verbose_name_plural": "LINE顧客",
            },
        ),
        migrations.CreateModel(
            name="LineWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhook_event_id",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Webhook event ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=40, verbose_name="イベント種別"),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "LINE Webhookイベント",
                "verbose_name_plural": "LINE Webhookイベント",
                "ordering": ("-processed_at",),
            },
        ),
        migrations.AddField(
            model_name="order",
            name="payment_link_version",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="支払いリンク版"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_request_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                editable=False,
                max_digits=12,
                null=True,
                verbose_name="支払い案内時金額",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_url",
            field=models.URLField(blank=True, verbose_name="追跡URL"),
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="TWD", max_length=3, verbose_name="通貨"),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_event_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Provider event ID",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="line_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="orders.linecustomer",
                verbose_name="LINE購入者",
            ),
        ),
        migrations.CreateModel(
            name="LineNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_received", "注文受付"),
                            ("payment_request", "支払い案内"),
                            ("payment_confirmed", "入金確認"),
                            ("order_shipped", "発送通知"),
                        ],
                        max_length=32,
                        verbose_name="通知種別",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "送信中"),
                            ("sent", "送信済み"),
                            ("failed", "失敗"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "dedupe_key",
                    models.CharField(max_length=160, verbose_name="重複防止キー"),
                ),
                (
                    "api_retry_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="LINE retry key",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="送信日時"
                    ),
                ),
                (
                    "failed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="失敗日時"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="再試行回数"),
                ),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="HTTP status"
                    ),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=255, verbose_name="エラー"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "line_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="orders.linecustomer",
                        verbose_name="LINE顧客",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_notifications",
                        to="orders.order",
                        verbose_name="注文",
                    ),
                ),
            ],
            options={
                "verbose_name": "LINE通知",
                "verbose_name_plural": "LINE通知",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "notification_type", "dedupe_key"),
                        name="unique_line_notification_delivery",
                    )
                ],
            },
        ),
    ]
