# Generated by Django 5.2.17 on 2026-08-10 14:00

import core.validators
import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_linecustomer_linewebhookevent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="linecustomer",
            options={"verbose_name": "LINE 顧客", "verbose_name_plural": "LINE 顧客"},
        ),
        migrations.AlterModelOptions(
            name="linewebhookevent",
            options={
                "ordering": ("-processed_at",),
                "verbose_name": "LINE Webhook 事件",
                "verbose_name_plural": "LINE Webhook 事件",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "訂單",
                "verbose_name_plural": "訂單",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "訂單明細", "verbose_name_plural": "訂單明細"},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "付款記錄",
                "verbose_name_plural": "付款記錄",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "ordering": ("sort_order", "pk"),
                "verbose_name": "付款方式設定",
                "verbose_name_plural": "付款方式設定",
            },
        ),
        migrations.AlterField(
            model_name="linecustomer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="linecustomer",
            name="display_name",
            field=models.CharField(max_length=160, verbose_name="LINE 顯示名稱"),
        ),
        migrations.AlterField(
            model_name="linecustomer",
            name="followed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="加好友時間"
            ),
        ),
        migrations.AlterField(
            model_name="linecustomer",
            name="friend_checked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="好友狀態確認時間"
            ),
        ),
        migrations.AlterField(
            model_name="linecustomer",
            name="is_blocked",
            field=models.BooleanField(default=False, verbose_name="已封鎖"),
        ),
        migrations.AlterField(
            model_name="linecustomer",
            name="is_friend",
            field=models.BooleanField(default=False, verbose_name="已加好友"),
        ),
        migrations.AlterField(
            model_name="linecustomer",
            name="last_login_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最後登入時間"
            ),
        ),
        migrations.AlterField(
            model_name="linecustomer",
            name="picture_url",
            field=models.URLField(blank=True, verbose_name="大頭貼網址"),
        ),
        migrations.AlterField(
            model_name="linecustomer",
            name="unfollowed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="封鎖時間"),
        ),
        migrations.AlterField(
            model_name="linecustomer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
        migrations.AlterField(
            model_name="linenotification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="linenotification",
            name="dedupe_key",
            field=models.CharField(max_length=160, verbose_name="防止重複傳送金鑰"),
        ),
        migrations.AlterField(
            model_name="linenotification",
            name="error_message",
            field=models.CharField(blank=True, max_length=255, verbose_name="錯誤訊息"),
        ),
        migrations.AlterField(
            model_name="linenotification",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="失敗時間"),
        ),
        migrations.AlterField(
            model_name="linenotification",
            name="line_customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="orders.linecustomer",
                verbose_name="LINE 顧客",
            ),
        ),
        migrations.AlterField(
            model_name="linenotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("order_received", "訂單成立"),
                    ("payment_request", "付款通知"),
                    ("payment_confirmed", "付款確認"),
                    ("order_shipped", "出貨通知"),
                ],
                max_length=32,
                verbose_name="通知類型",
            ),
        ),
        migrations.AlterField(
            model_name="linenotification",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_notifications",
                to="orders.order",
                verbose_name="訂單",
            ),
        ),
        migrations.AlterField(
            model_name="linenotification",
            name="retry_count",
            field=models.PositiveIntegerField(default=0, verbose_name="重試次數"),
        ),
        migrations.AlterField(
            model_name="linenotification",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="傳送時間"),
        ),
        migrations.AlterField(
            model_name="linenotification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "傳送中"),
                    ("sent", "已傳送"),
                    ("failed", "傳送失敗"),
                ],
                default="pending",
                max_length=16,
                verbose_name="傳送狀態",
            ),
        ),
        migrations.AlterField(
            model_name="linenotification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
        migrations.AlterField(
            model_name="linewebhookevent",
            name="event_type",
            field=models.CharField(max_length=40, verbose_name="事件類型"),
        ),
        migrations.AlterField(
            model_name="linewebhookevent",
            name="processed_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="處理時間"),
        ),
        migrations.AlterField(
            model_name="order",
            name="access_token",
            field=models.CharField(
                default=orders.models.generate_access_token,
                editable=False,
                max_length=64,
                unique=True,
                verbose_name="顧客存取金鑰",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="admin_note",
            field=models.TextField(blank=True, verbose_name="管理備註"),
        ),
        migrations.AlterField(
            model_name="order",
            name="carrier",
            field=models.CharField(blank=True, max_length=120, verbose_name="物流公司"),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_note",
            field=models.TextField(blank=True, verbose_name="顧客備註"),
        ),
        migrations.AlterField(
            model_name="order",
            name="final_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                editable=False,
                max_digits=12,
                null=True,
                verbose_name="訂單總額",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="idempotency_key",
            field=models.CharField(
                editable=False,
                max_length=128,
                unique=True,
                verbose_name="防止重複送出金鑰",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="inventory_released",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="庫存已還原"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="inventory_reserved",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="庫存已保留"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="line_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="orders.linecustomer",
                verbose_name="LINE 購買者",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="付款確認時間"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_link_version",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="付款連結版本"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_request_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                editable=False,
                max_digits=12,
                null=True,
                verbose_name="付款通知金額",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="public_number",
            field=models.CharField(
                default=orders.models.generate_order_number,
                editable=False,
                max_length=32,
                unique=True,
                verbose_name="訂單編號",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="出貨時間"),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="運費",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_information",
            field=models.TextField(verbose_name="收件與配送資訊"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "訂單已成立"),
                    ("shipping_review", "運費確認中"),
                    ("awaiting_payment", "等待付款"),
                    ("paid", "已付款"),
                    ("preparing", "出貨準備中"),
                    ("shipped", "已出貨"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="received",
                max_length=32,
                verbose_name="訂單狀態",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=0, max_digits=12, verbose_name="商品小計"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=160, verbose_name="追蹤號碼"),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_url",
            field=models.URLField(blank=True, verbose_name="追蹤網址"),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
                verbose_name="訂單",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_name_snapshot",
            field=models.CharField(max_length=220, verbose_name="商品名稱快照"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="數量"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="sku_snapshot",
            field=models.CharField(blank=True, max_length=80, verbose_name="SKU 快照"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="stock_was_reserved",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="已保留一般庫存"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price_snapshot",
            field=models.DecimalField(
                decimal_places=0, max_digits=12, verbose_name="單價快照"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="付款金額",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="TWD", max_length=3, verbose_name="幣別"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="orders.paymentmethod",
                verbose_name="付款方式",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="note",
            field=models.TextField(blank=True, verbose_name="備註"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="orders.order",
                verbose_name="訂單",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="付款時間"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="金流服務商"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider_event_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="金流事件 ID",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider_reference",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="金流參考編號"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待處理"),
                    ("awaiting_confirmation", "等待確認"),
                    ("confirmed", "已確認"),
                    ("failed", "失敗"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=32,
                verbose_name="付款狀態",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="code",
            field=models.CharField(
                choices=[
                    ("taiwan_pay", "台灣 Pay"),
                    ("credit_card", "信用卡"),
                    ("bank_transfer", "銀行轉帳"),
                    ("paypal", "PayPal"),
                ],
                max_length=32,
                unique=True,
                verbose_name="付款方式",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="display_name",
            field=models.CharField(max_length=120, verbose_name="顯示名稱"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="enabled",
            field=models.BooleanField(default=False, verbose_name="啟用"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="instructions",
            field=models.TextField(blank=True, verbose_name="付款說明"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="provider",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="金流服務商"
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="qr_image",
            field=models.ImageField(
                blank=True,
                upload_to="payments/methods/",
                validators=[core.validators.validate_image_upload],
                verbose_name="QR 圖片",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="顯示順序"),
        ),
    ]
