# Generated by Django 5.2.17 on 2026-08-11 02:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def preserve_duplicate_confirmed_payments(apps, schema_editor):
    Payment = apps.get_model("orders", "Payment")
    duplicate_orders = (
        Payment.objects.filter(status="confirmed")
        .values_list("order_id", flat=True)
        .order_by("order_id")
    )
    seen = set()
    for order_id in duplicate_orders.iterator():
        if order_id in seen:
            # Preserve the accounting row and amount; only classify additional
            # confirmed receipts as overpayments before adding the invariant.
            extra = Payment.objects.filter(order_id=order_id, status="confirmed").order_by("paid_at", "created_at", "pk")[1:]
            Payment.objects.filter(pk__in=[payment.pk for payment in extra]).update(status="overpaid")
        seen.add(order_id)


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_linecustomer_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("line", "LINE"), ("email", "Email")],
                        max_length=16,
                        verbose_name="管道",
                    ),
                ),
                ("event_type", models.CharField(max_length=40, verbose_name="事件")),
                (
                    "dedupe_key",
                    models.CharField(max_length=180, verbose_name="冪等金鑰"),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="工作資料"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待傳送"),
                            ("processing", "傳送中"),
                            ("retry", "等待重試"),
                            ("sent", "已傳送"),
                            ("dead", "人工處理"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(default=0, verbose_name="嘗試次數"),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=8, verbose_name="最大嘗試次數"
                    ),
                ),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="下次嘗試"
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="鎖定時間"
                    ),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="最後錯誤")),
                (
                    "response_metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="回應資料"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="傳送時間"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "通知佇列",
                "verbose_name_plural": "通知佇列",
                "ordering": ("next_attempt_at", "pk"),
            },
        ),
        migrations.CreateModel(
            name="OrderAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=40, verbose_name="操作")),
                (
                    "actor_label",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="操作來源"
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="變更前狀態"
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="變更後狀態"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(blank=True, default=dict, verbose_name="變更內容"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="補充資料"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作時間"),
                ),
            ],
            options={
                "verbose_name": "訂單監査記錄",
                "verbose_name_plural": "訂單監査記錄",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="PolicyAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(max_length=80, verbose_name="文件類型"),
                ),
                ("version", models.CharField(max_length=40, verbose_name="版本")),
                (
                    "accepted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="同意時間"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, max_length=300, verbose_name="瀏覽器"),
                ),
            ],
            options={
                "verbose_name": "政策同意記錄",
                "verbose_name_plural": "政策同意記錄",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="cancel_link_version",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="取消連結版本"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="取消時間"),
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=60, verbose_name="縣市"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_note",
            field=models.CharField(blank=True, max_length=300, verbose_name="配送備註"),
        ),
        migrations.AddField(
            model_name="order",
            name="district",
            field=models.CharField(blank=True, max_length=80, verbose_name="鄉鎮市區"),
        ),
        migrations.AddField(
            model_name="order",
            name="postal_code",
            field=models.CharField(blank=True, max_length=12, verbose_name="郵遞區號"),
        ),
        migrations.AddField(
            model_name="order",
            name="public_id",
            field=models.UUIDField(
                blank=True, editable=False, null=True, verbose_name="內部安全識別碼"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="recipient_name",
            field=models.CharField(blank=True, max_length=160, verbose_name="收件人"),
        ),
        migrations.AddField(
            model_name="order",
            name="street_address",
            field=models.CharField(blank=True, max_length=300, verbose_name="街道地址"),
        ),
        migrations.AddField(
            model_name="payment",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="取消時間"),
        ),
        migrations.AddField(
            model_name="payment",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="確認時間"),
        ),
        migrations.AddField(
            model_name="payment",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                max_length=160,
                null=True,
                unique=True,
                verbose_name="付款冪等金鑰",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_metadata",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="金流回應資料"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="refund_operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operated_refunds",
                to=settings.AUTH_USER_MODEL,
                verbose_name="退款操作人",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="refund_reason",
            field=models.TextField(blank=True, verbose_name="退款原因"),
        ),
        migrations.AddField(
            model_name="payment",
            name="refund_status",
            field=models.CharField(blank=True, max_length=32, verbose_name="退款狀態"),
        ),
        migrations.AddField(
            model_name="payment",
            name="refunded_amount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="退款金額"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="退款時間"),
        ),
        migrations.AlterField(
            model_name="linenotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("order_received", "訂單成立"),
                    ("payment_request", "付款通知"),
                    ("payment_confirmed", "付款確認"),
                    ("order_shipped", "出貨通知"),
                    ("order_cancelled", "取消通知"),
                ],
                max_length=32,
                verbose_name="通知類型",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "訂單已成立"),
                    ("shipping_review", "運費確認中"),
                    ("awaiting_payment", "等待付款"),
                    ("paid", "已付款"),
                    ("preparing", "出貨準備中"),
                    ("shipped", "已出貨"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                    ("refund_pending", "退款處理中"),
                    ("refunded", "已退款"),
                ],
                default="received",
                max_length=32,
                verbose_name="訂單狀態",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待處理"),
                    ("awaiting_confirmation", "等待確認"),
                    ("confirmed", "已確認"),
                    ("failed", "失敗"),
                    ("cancelled", "已取消"),
                    ("partially_refunded", "部分退款"),
                    ("refunded", "全額退款"),
                    ("overpaid", "過入金"),
                    ("chargeback", "爭議款／拒付"),
                ],
                default="pending",
                max_length=32,
                verbose_name="付款狀態",
            ),
        ),
        migrations.RunPython(preserve_duplicate_confirmed_payments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "confirmed")),
                fields=("order",),
                name="one_confirmed_payment_per_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("refunded_amount__gte", 0)),
                name="payment_refund_amount_nonnegative",
            ),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_outbox",
                to="orders.order",
                verbose_name="訂單",
            ),
        ),
        migrations.AddField(
            model_name="orderauditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="後台操作人",
            ),
        ),
        migrations.AddField(
            model_name="orderauditlog",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_logs",
                to="orders.order",
                verbose_name="訂單",
            ),
        ),
        migrations.AddField(
            model_name="policyacceptance",
            name="line_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="policy_acceptances",
                to="orders.linecustomer",
                verbose_name="顧客",
            ),
        ),
        migrations.AddField(
            model_name="policyacceptance",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="policy_acceptances",
                to="orders.order",
                verbose_name="訂單",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationoutbox",
            index=models.Index(
                fields=["status", "next_attempt_at"],
                name="orders_noti_status_1155b1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationoutbox",
            constraint=models.UniqueConstraint(
                fields=("channel", "event_type", "dedupe_key"),
                name="unique_outbox_delivery",
            ),
        ),
        migrations.AddIndex(
            model_name="orderauditlog",
            index=models.Index(
                fields=["order", "created_at"], name="orders_orde_order_i_10a437_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderauditlog",
            index=models.Index(
                fields=["event", "created_at"], name="orders_orde_event_32eb57_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyacceptance",
            constraint=models.UniqueConstraint(
                fields=("order", "document_type", "version"),
                name="unique_order_policy_acceptance",
            ),
        ),
    ]
