# Generated by Django 5.2.17 on 2026-08-11 02:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_populate_order_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="public_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="內部安全識別碼",
            ),
        ),
    ]
