# Generated by Django 5.2.17 on 2026-09-01 08:43

from django.conf import settings
from django.db import migrations, models


def configure_ecpay_credit_card(apps, schema_editor):
    PaymentMethod = apps.get_model("orders", "PaymentMethod")
    PaymentMethod.objects.filter(code="credit_card", provider="").update(provider="ecpay")


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_public_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="merchant_trade_no",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="特店交易編號",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("provider", "ecpay"),
                    models.Q(("provider_reference", ""), _negated=True),
                ),
                fields=("provider_reference",),
                name="unique_ecpay_trade_no",
            ),
        ),
        migrations.RunPython(configure_ecpay_credit_card, migrations.RunPython.noop),
    ]
