# Generated by Django 5.2.17 on 2026-10-03 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_localize_payment_and_audit_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInvoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('personal', '個人電子發票'), ('mobile_barcode', '手機條碼載具'), ('company', '公司用電子發票')], default='personal', max_length=24, verbose_name='發票類型')),
                ('customer_identifier', models.CharField(blank=True, max_length=8, verbose_name='統一編號')),
                ('customer_name', models.CharField(blank=True, max_length=60, verbose_name='發票抬頭／公司名稱')),
                ('carrier_type', models.CharField(blank=True, max_length=1, verbose_name='載具類別')),
                ('carrier_number', models.CharField(blank=True, max_length=64, verbose_name='載具編號')),
                ('email', models.EmailField(max_length=254, verbose_name='發票 Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='發票電話')),
                ('configuration_snapshot', models.JSONField(blank=True, default=dict, verbose_name='建立時發票設定快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_profile', to='orders.order', verbose_name='訂單')),
            ],
            options={
                'verbose_name': '訂單發票資訊',
                'verbose_name_plural': '訂單發票資訊',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='ecpay', editable=False, max_length=32, verbose_name='服務商')),
                ('status', models.CharField(choices=[('pending', '發票待處理'), ('issuing', '開立中'), ('issued', '已開立'), ('failed', '開立失敗'), ('review_required', '需要人工確認'), ('voided', '已作廢')], default='pending', max_length=24, verbose_name='狀態')),
                ('relate_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='特店自訂編號')),
                ('invoice_no', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='發票號碼')),
                ('invoice_date', models.DateTimeField(blank=True, null=True, verbose_name='開立日期')),
                ('random_number', models.CharField(blank=True, max_length=4, verbose_name='隨機碼')),
                ('sales_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='發票總額')),
                ('customer_identifier', models.CharField(blank=True, max_length=8, verbose_name='統一編號')),
                ('carrier_type', models.CharField(blank=True, max_length=1, verbose_name='載具類別')),
                ('error_code', models.CharField(blank=True, max_length=64, verbose_name='錯誤代碼')),
                ('error_message', models.CharField(blank=True, max_length=300, verbose_name='最近一次錯誤')),
                ('provider_metadata', models.JSONField(blank=True, default=dict, verbose_name='服務商回應摘要')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='嘗試次數')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='最近嘗試時間')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='開立完成時間')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='作廢時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order', verbose_name='訂單')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orders.orderinvoiceprofile', verbose_name='發票資訊快照')),
            ],
            options={
                'verbose_name': '電子發票',
                'verbose_name_plural': '電子發票',
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('sales_amount__gt', 0)), name='invoice_sales_amount_positive')],
            },
        ),
    ]
